In [9]:
import numpy as np
import pandas as pd
import random
from sklearn.linear_model import LinearRegression


# Контрольні дані
print("Контрольна модель. Точки по двом фічерам лежать на прямій")
#Ваги
ws = np.array([5, 2, 7])
print(f"Ваги {ws}")

# Аргументи
ags = np.array([[3, 5], [4, 2], [12, 7], [18, 3]])
print(f"Фічери {ags}")

# Контрольны результати
ress = np.array([46, 27, 78, 62])
ress = ress.reshape(len(ress), 1)
print(f"Значення точок {ress}")

"""
Тут не дивимось, окремі досліди до 2 уроку

# Функція гіпотези, повертає вектор з результатами для заданих параметрів (ваги)
# Матриця з аргументами, вектор з вагами
# В результаті множення вектор з результатами
def h_matrix(m_args:np.ndarray, v_weights:np.ndarray):
    # В матрицю аргументів додаємо перший стовбчик з одиницями
    # Ваги примусово перетворюэмо у вектор
    return np.append(np.ones((len(m_args), 1)),  m_args, axis=1) @ v_weights.reshape((len(v_weights), 1))

# Функція втрат, повертає СКВ між даними по гіпотезі та фактичними даними
def cost_matrix(results, control):
    #print(results)
    #print(results - control)
    # Повертаємо середню суму квадратів різниць
    return np.sum((results - control) ** 2) / (len(results) * 2)


# h_result = h_matrix(ags, np.array([5, 2, 7]))
# print(cost_matrix(h_result, ress))

def try_zero_to_ten(m_args, v_weights, idx, control):
    res = []
    for i in range(11):
        cur_weights = np.copy(v_weights)
        cur_weights[idx] = i
        res.append([cur_weights, cost_matrix(h_matrix(m_args, cur_weights), control)])
    
    print(res)

    return res

#try_zero_to_ten(ags, ws, 0, ress)
"""
class LinRegr:
    def __init__(self, learn_rate: float = 0.001, trash_hold: float = 0.00001, n_epoch: float = 100, n_w = 2, show_progress = False) -> float:
        self.lr = learn_rate
        self.th = trash_hold
        self.n_epoch = n_epoch
        self.w = np.array([random.uniform(0, 10) for i in range(n_w)]).reshape(n_w, 1)
        self.show_progress = show_progress
        self.X = np.array([])
        self.Y = np.array([])

    def guess_w(self):
        avg_y = np.mean(self.Y)
        print(self.w)
        #print(np.mean(self.X) / avg_y)
        print(np.mean(self.X, axis=1))
        print(avg_y)
        avg_x = np.array(np.mean(self.X))
        self.w = avg_x.reshape(len(avg_x, 1)) / avg_y
        print("guess")
        print(self.w)
        


    def predict(self):
        return self.X @ self.w
        #v_weights = np.array(self.w)
        #return np.append(np.ones((len(m_args), 1)),  m_args, axis=1) @ v_weights.reshape((len(v_weights), 1))
    
    def update_w(self):
        v_h = self.predict()
        m = len(self.w)
        self.w = self.w - self.lr / m * self.X.T @ (v_h - self.Y)
        # Приводимо до стандартного виду з першою 1
        #__m_x = np.append(np.ones((len(m_x), 1)),  m_x, axis=1)
        #sm = [0 for i in range(m)]
        
        #for xi, hi, yi in zip(__m_x, v_h, m_y):
        #    for j in range(m):
        #        sm[j] += (hi - yi) * xi[j]
        
        #updated = False

        #print(np.array(self.w).reshape(m, 1) - self.lr / m * __m_x.T @ (v_h - m_y))

        #print(self.lr / m * __m_x.T @ (v_h - m_y))

        #for j in range(m):
        #    self.w[j] = self.w[j] - self.lr * sm[j]/m
            #if abs(new_w - self.w[j]) > self.th:
            #    self.w[j] = new_w
            #    updated = True
            
        #return True

    def cost(self, v_predict):
        return np.sum((v_predict - self.Y) ** 2) / (len(v_predict) * 2)

    def fit(self, m_x, m_y):
        # Приводимо один раз дані до потрібної форми
        self.X = np.append(np.ones((len(m_x), 1)),  m_x, axis=1)
        self.Y = m_y.reshape(len(m_y), 1)
        #self.guess_w()
        #print(self.w)

        # Старий кост зі словника Стеля
        old_cost = 10000000
        for i in range(self.n_epoch):
            self.update_w()
            #if not self.update_w(m_x, m_y):
            #    break
            #print(self.predict(m_x))
            cur_cost = self.cost(self.predict())

            if self.show_progress:
                print(f"{i} {cur_cost}")
            
            if abs(old_cost - cur_cost) < self.th:
                break
            else:
                old_cost = cur_cost



print("Навчання моделі на контрольних даних")
li_re = LinRegr(n_w = len(ws), n_epoch=100000, learn_rate=0.002, trash_hold=0.0000000001, show_progress=False)
li_re.fit(ags, ress)
print(f"Ваги, отримані моделлю {li_re.w}")

print("sklearn")
box_lr = LinearRegression()
box_lr.fit(ags, ress)
print(box_lr.coef_)
print(box_lr.intercept_)

print("Normal equation")
def nor_eq(x, y):
    mtx_x = np.append(np.ones((len(x), 1)),  x, axis=1)
    mtx_x_t = mtx_x.T
    return np.linalg.inv(mtx_x_t @ mtx_x) @ mtx_x_t @ y

print(nor_eq(ags, ress))
    

print("Зчитування даних csv")
df = pd.read_csv("Housing.csv")
##print(df.iloc[0:,0:1])
prices = pd.DataFrame(df, columns=["price"]).to_numpy()
prices_non_sc = prices.copy()

min_p = np.min(prices)
max_p = np.max(prices)

for i in range(len(prices)):
    prices[i] = (prices[i] - min_p)/(max_p - min_p)
#print(np.max(prices))
#print(np.min(prices))
#print(prices)
features = pd.DataFrame(df, columns=["area", "bathrooms", "bedrooms"]).to_numpy()
features_non_sc = features.copy()

max_f = np.max(features, axis=0)
min_f = np.min(features, axis=0)

for i in range(len(features)):
    for j in range(len(max_f)):
        features[i][j] = (features[i][j] - min_f[j]) / (max_f[j] - min_f[j])
#print(np.max(features, axis=0))
#print(np.min(features, axis=0))


print("NE for prices")
print(nor_eq(features_non_sc, prices_non_sc))

li_re_price = LinRegr(n_w= 4, n_epoch=100000, learn_rate=0.002, trash_hold=0.0000000001, show_progress=False)
li_re_price.fit(np.array(features), np.array(prices))
print(f"Ваги, отримані моделлю для нормалізованих даних prices {li_re_price.w}")

print("NE for prices нормалізовані дані")
print(nor_eq(features, prices))

print("sklearn для нормалізованих даних")
box_lr.fit(features, prices)
print(box_lr.coef_)
print(box_lr.intercept_)


print("Нормалізуємо тільки площу діленням на 4000 (експертна оцінка, приблизно максимум / 4 [приблизний максимум по решті іксів])")
features_4000 = features_non_sc.copy()
for i in range(len(features_4000)):
    features_4000[i][0] = features_4000[i][0] / 4000

li_re_price.fit(np.array(features_4000), np.array(prices))
print(f"Ваги, отримані моделлю для нормалізованих даних 4000 prices {li_re_price.w}")

print("sklearn")
box_lr.fit(features_non_sc, prices_non_sc)
print(box_lr.coef_)
print(box_lr.intercept_)

as_resume = """Замість висновків:
1. На тестових даних розроблена модель дає параметри, близькі до точних, але не справляється настільки ж добре, як sklearn чи Normal equation 
2. На ненормалізованих даних модель не працює, sklearn чи Normal equation дають приблизно однакові результати
3. На нормалізованих даних три моделі дають близькі значення, однак розроблена вимагає значно більше часу і все одно не є настільки точною
3.1 Треба оптимізувати і вчитись
3.2 Не розібрався, як приводити ваги, отримані на нормалізованих даних, до вагів з ненормалізованими даними
4. Варіант з Normal equation виглядає зручним в застосуванні, але має певні обмеження:
- на великих наборах працюватиме довше
- існують матриці, для яких розрахувати обернену неможливо


"""

Контрольна модель. Точки по двом фічерам лежать на прямій
Ваги [5 2 7]
Фічери [[ 3  5]
 [ 4  2]
 [12  7]
 [18  3]]
Значення точок [[46]
 [27]
 [78]
 [62]]
Навчання моделі на контрольних даних
Ваги, отримані моделлю [[4.99849766]
 [2.00004173]
 [7.00021762]]
sklearn
[[2. 7.]]
[5.]
Normal equation
[[5.]
 [2.]
 [7.]]
Зчитування даних csv
NE for prices
[[-1.73171608e+05]
 [ 3.78762754e+02]
 [ 1.38604950e+06]
 [ 4.06820034e+05]]
Ваги, отримані моделлю для нормалізованих даних prices [[ 0.00182153]
 [ 0.00383687]
 [ 0.00694691]
 [-0.0017733 ]]
NE for prices нормалізовані дані
[[ 0.00184843]
 [-0.00184843]
 [-0.00184843]
 [-0.00184843]]
sklearn для нормалізованих даних
[[-0.00184843 -0.00184843 -0.00184843]]
[0.00184843]
Нормалізуємо тільки площу діленням на 4000 (експертна оцінка, приблизно максимум / 4 [приблизний максимум по решті іксів])


C:\Users\maxim\AppData\Roaming\Python\Python39\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\maxim\AppData\Local\Temp\ipykernel_22992\2906251058.py:133: RuntimeWarning: invalid value encountered in scalar subtract
  if abs(old_cost - cur_cost) < self.th:
C:\Users\maxim\AppData\Local\Temp\ipykernel_22992\2906251058.py:112: RuntimeWarning: overflow encountered in square
  return np.sum((v_predict - self.Y) ** 2) / (len(v_predict) * 2)
C:\Users\maxim\AppData\Local\Temp\ipykernel_22992\2906251058.py:81: RuntimeWarning: overflow encountered in matmul
  return self.X @ self.w
C:\Users\maxim\AppData\Local\Temp\ipykernel_22992\2906251058.py:88: RuntimeWarning: invalid value encountered in matmul
  self.w = self.w - self.lr / m * self.X.T @ (v_h - self.Y)


Ваги, отримані моделлю для нормалізованих даних 4000 prices [[nan]
 [nan]
 [nan]
 [nan]]
sklearn
[[3.78762754e+02 1.38604950e+06 4.06820034e+05]]
[-173171.60763264]


In [ ]:
# Цікаві досліди